// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.TradesAdapter.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Trade
    {
        /// <summary>
        /// Initializes a new instance of the Trade class.
        /// </summary>
        public Trade()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Trade class.
        /// </summary>
        /// <param name="action">Possible values include: 'Buy', 'Sell'</param>
        public Trade(System.DateTime dateTime, double volume, double price, TradeAction action, string id = default(string), string assetPairId = default(string))
        {
            Id = id;
            AssetPairId = assetPairId;
            DateTime = dateTime;
            Volume = volume;
            Price = price;
            Action = action;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPairId")]
        public string AssetPairId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public System.DateTime DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double Price { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Buy', 'Sell'
        /// </summary>
        [JsonProperty(PropertyName = "Action")]
        public TradeAction Action { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
